### ISSUE TITLE
Debian Jessie script provided.

### ISSUE THREAD

**Issue by george-vieira** [zeysh/centreon-install#12]
Awesome script, saved me hours and pain. I modified it to work with debian jessie and placed a copy on http://www.emperor-it.com/downloads/centreon-installer.sh as I didnt want to fork it. It still says Wheezy and theres commented out repo which with jessie is not required and cleaner install so up to you how you'd like to do it (another reason not to fork). Diff and take whatever changes (not much anyway).

The only thing it doesn't do is the apache config as centreon uses /etc/apache2/conf.d which doesn't exist.
So I just added manually:
 # cat > /etc/apache2/conf-available/centreon.conf << EOF
Alias /centreon /usr/local/centreon/www/
<Directory "/usr/local/centreon/www">
        Options Indexes
        AllowOverride AuthConfig Options
        Order allow,deny
        Allow from all
        Require all granted
</Directory>
EOF

ln -s /etc/apache2/conf-available/conf-available/centreon.conf /etc/apache2/conf-enabled/centreon.conf

Versions used and confirmed to work as below.
root@qetesh:/home/eitadmin # ./centreon-installer.sh

=======================| Install details |============================

```
              MariaDB    : 10.0
              Clib       : 1.4.2
              Connector  : 1.1.1
              Engine     : 1.4.14
              Plugin     : 2.0.3
              Broker     : 2.8.2
              Centreon   : 2.6.1
              Install dir: /usr/local
              Source dir : /usr/local/src
```
# 

Step1  => Install MariaDB                                       [ OK ]
Step2  => Install PHP5.3 on Wheezy                              [ OK ]
Step3  => Clib install                                          [ OK ]
Step4  => Centreon Perl and SSH connectors install              [ OK ]
Step5  => Centreon Engine install                               [ OK ]
Step6  => Nagios plugins install                                [ OK ]
Step6  => Centreon plugins install                              [ OK ]
Step7  => Centreon Broker install                               [ OK ]
Step8  => Centreon template generation                          [ OK ]
Step9  => Centreon web interface install                        [ OK ]
Step10 => Post install                                          [ OK ]
Step11 => CLAPI install                                         [ OK ]
Step12 => Widgets install                                       [ OK ]

Go to http://172.16.200.110/centreon to complete the setup

**Comment by george-vieira** [comment]
oh just to add.. instead of adding the paths for the gui. couldn't we simply replace their 'vars' file as below shows?

eitadmin@qetesh:/usr/local/src/centreon-2.6.1 $ cat varinstall/vars

# -_-Shell-script-_-

# install_vars

# This file contain reconfigured variables used in install scripts

LOG_DIR="$BASE_DIR/log"
LOG_FILE="$LOG_DIR/install_centreon.log"
TMP_DIR="/tmp/centreon-setup"
SNMP_DIR="/etc/snmp/"
CENTREON_CONF_1_4="/etc/[co][er][ne][to][rn]*.conf"
DEFAULT_CENTREON_CONF="/etc/centreon/centreon.conf"
CENTREON_CONF="/etc/centreon.conf"
#use $CENTREON_ETC/centreon.conf
PEAR_MODULES_LIST="pear.lst"
DEFAULT_INSTALL_DIR_NAGIOS="/usr/local/nagios"
DEFAULT_INSTALL_DIR_CENTREON="/usr/local/centreon"
DEFAULT_RRD_PERL="/usr/lib/perl5"
DEFAULT_SUDO_FILE="/etc/sudoers"
DEFAULT_WEB_USER="www-data"
DEFAULT_WEB_GROUP="www-data"
DEFAULT_NAGIOS_USER="nagios"
DEFAULT_NAGIOS_GROUP="nagcmd"
DEFAULT_BIN_RRDTOOL="/usr/bin/rrdtool"
DEFAULT_BIN_MAIL="/usr/bin/mail"
DEFAULT_BIN_SSH="/usr/bin/ssh"
DEFAULT_BIN_SCP="/usr/bin/scp"
DEFAULT_INIT_D="/etc/init.d"
DEFAULT_CRON_D="/etc/cron.d"
DEFAULT_PEAR_PATH="/usr/share/php"
DEFAULT_PHP_BIN="/usr/bin/php"
DEFAULT_PERL_BIN="/usr/bin/perl"
DEFAULT_CENTREON_LOG="/usr/local/centreon/log"
DEFAULT_CENTREON_ETC="/etc/centreon"
DEFAULT_CENTREON_RUNDIR="/var/run/centreon"
DEFAULT_CENTREON_GENDIR="/usr/local/centreon"
DEFAULT_CENTREON_VARLIB="/var/lib/centreon"
DEFAULT_CENTSTORAGE_RRD="/var/lib/centreon"
DEFAULT_CENTPLUGINS_TMP="/var/lib/centreon/centplugins"
DEFAULT_CENTSTORAGE_BINDIR="bin"
DEFAULT_CENTCORE_BINDIR="bin"
DEFAULT_SNMP_ETC="/etc/snmp"
DEFAULT_SNMPTT_BINDIR="/usr/local/centreon/bin/"
DEFAULT_CENTPLUGINSTRAPS_BINDIR="/usr/local/centreon/bin"
DEFAULT_CENTREON_USER="centreon"
DEFAULT_CENTREON_GROUP="centreon"
DEFAULT_PLUGIN_DIR="/usr/lib/nagios/plugins"
DEFAULT_CENTREON_BINDIR="/usr/local/centreon/bin"
DEFAULT_CENTREON_DATADIR="/usr/local/centreon/data"

**Comment by albundy83** [comment]
Hello,

if you want an updated version that support directly Debian Jessie and latest release, you can check the fork : 
https://github.com/GreenCom-Networks/centreon-install
Enjoy.

**Comment by george-vieira** [comment]
Forked my own which also fills out the paths correctly making it even easier to just select Broker and click next.
Your fork is missing libsnmp-perl which is required for centreontrapd service to start btw.

**Comment by albundy83** [comment]
Ah yes, you are right.
Thanks.

**Comment by george-vieira** [comment]
Also noticed there's some issue with centcore and an strace shows it's looking for cmd file in wrong path:
stat("/var/lib/centreon/centcore.cmd", 0x1be7238) = -1 ENOENT (No such file or directory)
stat("/var/lib/centreon/centcore/", 0x1be7238) = -1 ENOENT (No such file or directory)

But the /etc/centreon/conf.pm config file contains:
\ # Centreon Centcore Command File
$cmdFile = "/var/lib/centreon-engine/rw/centengine.cmd";

which I'm now confused as their /usr/share/perl5/centreon/script/centcore.pm library files appears to use centcore.cmd but the /etc/centreon/conf.pm specifies the centreon-engine cmd file.

Now I'm confused what uses what, talks to what via what.lol. 
Is this some mis configuration from the install?

What brought me to this issue is that I can't acknowledge services or hosts. simply nothing happens.

**Comment by albundy83** [comment]
Hello,

which version are you using, as I have now moved to Centreon Web 2.7...
Where do you see this error ?

**Comment by george-vieira** [comment]
ignore it, worked it out to be permission issue on /var/lib/centreon which was possibly caused when I moved that path to a new disk volume due to it's massive size and somehow made it 755 rather than 775.
I find it really stupid that centreon uses passthru() to blindly write into a unix socket and not monitor errors from it hence why I endured so much pain trying to find the cause.
