### ISSUE TITLE
Version upgrade (not an issue)

### ISSUE THREAD

**Issue by albundy83** [zeysh/centreon-install#5]
Hello,

just to inform you that I have try your script and I have bumped the version to the latest release available : 
CLIB_VER="1.4.2"
CONNECTOR_VER="1.1.1"
ENGINE_VER="1.4.11"
PLUGIN_VER="2.0.3"
BROKER_VER="2.8.1"
CENTREON_VER="2.5.4"
CLAPI_VER="1.7.1"
# MariaDB Series
MARIADB_VER='5.5'

## Sources widgets
WIDGET_HOST_VER="1.3.2"
WIDGET_HOSTGROUP_VER="1.1.1"
WIDGET_SERVICE_VER="1.3.2"
WIDGET_SERVICEGROUP_VER="1.1.0"

It has worked perfectly.
Another test I have done, is to use your script to update my current "old" version (the version I have installed before were those which were in your original script).
All has worked perfectly.

Thanks again for this great script !!!

**Comment by zeysh** [comment]
Hello,

Good to know, I never test an upgrade atm. Could you push a PR with new versions ?

Many thanks

**Comment by albundy83** [comment]
Hello,

just performed differents request from my account.
albundy83 and my job email : gbg@greencom-networks.com


Have a good day.

2015-04-09 1:06 GMT+02:00 Zeysh <notifications@github.com>:

> Hello,
>
> Good to know, I never test an upgrade atm. Could you push a PR with new
> versions ?
>
> Many thanks
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/zeysh/centreon-install/issues/5#issuecomment-91063403>
> .
>



-- 

G. BELLON-GERVAIS
06.82.84.89.03
